name: Android-Test-Build-CI

env:
  application_name: Recipe App

on: [push, pull_request]

jobs:
  test-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
            build-scan-publish: true
            build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
            build-scan-terms-of-use-agree: "yes"

      # Run Lint
      - name: Run Lint
        run: ./gradlew lint

  build-project:
    needs: test-project
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
            build-scan-publish: true
            build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
            build-scan-terms-of-use-agree: "yes"

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Create APK Release
      - name: Build Release Version (APK)
        run: ./gradlew assemble

      - name: Rename Release Version (APK)
        run: mv "./app/build/outputs/apk/release/app-release-unsigned.apk" "./app/build/outputs/apk/release/${{ env.application_name }}.apk"

      - name: Upload Release Version (APK)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repository_name }}-${{ env.date_today }}-Version
          path: app/build/outputs/apk/release/${{ env.application_name }}.apk
